weights: yolov5s.pt
cfg: ''
data: "C:\\Users\\vanov\\OneDrive\\\u0420\u043E\u0431\u043E\u0447\u0438\u0439 \u0441\
  \u0442\u0456\u043B\\\u0414\u0437 \u0440\u043E\u0433\u0430\\\u041F\u0440\u0430\u043A\
  \u0442\u0438\u043A\u0430\\Prychantovskyi\\task5\\yolov5\\data\\yolo_2022.yaml"
hyp: data\hyps\hyp.scratch.yaml
epochs: 20
batch_size: 16
imgsz: 640
rect: false
resume: false
nosave: false
noval: false
noautoanchor: false
evolve: null
bucket: ''
cache: null
image_weights: false
device: ''
multi_scale: false
single_cls: false
optimizer: SGD
sync_bn: false
workers: 8
project: runs\train
name: exp
exist_ok: false
quad: false
linear_lr: false
label_smoothing: 0.0
patience: 100
freeze:
- 0
save_period: -1
local_rank: -1
entity: null
upload_dataset: false
bbox_interval: -1
artifact_alias: latest
save_dir: runs\train\exp25
